// enclave/enclave_grpc/src/lib.rs
//
// Phase 11 — Tokio Async Rust gRPC Enclave Core.
//
// Pulls in the code generated by build.rs from proto/enclave_service.proto
// and declares the module tree:
//   grpc_server  — EnclaveService server trait implementation (Prompt 204)
//   tls_config   — rustls mTLS server configuration (Prompt 206)
//   middleware   — tower rate limiting (Prompt 210)
//   attestation  — IETF RATS EAT / COSE-Sign1 (Phase 12, Prompt 223+)

pub mod attestation;
pub mod ftso_provider;
pub mod grpc_server;
pub mod kms;
pub mod metrics;
pub mod middleware;
pub mod tls_config;
pub mod zktls;

/// Generated protobuf/gRPC code. tonic-build 0.10 names the output after
/// the PROTO PACKAGE (enclave.v1) and emits message types at top level plus
/// <service>_client / <service>_server modules — verified against the actual
/// generated file in OUT_DIR.
pub mod proto {
    tonic::include_proto!("enclave.v1");
}

pub use proto::*;
